openapi: 3.0.0
info:
  title: Callback Example
  version: 1.0.0
paths:
  /streams:
    post:
      description: subscribes a client to receive out-of-band data
      parameters:
        - name: callbackUrl
          in: query
          required: true
          description: |
            the location where data will be sent.  Must be network accessible
            by the source server
          schema:
            type: string
            format: uri
            example: https://tonys-server.com
      responses:
        '201':
          description: subscription successfully created
          content:
            application/json:
              schema:
                description: subscription information
                required:
                  - subscriptionId
                properties:
                  subscriptionId:
                    description: this unique identifier allows management of the subscription
                    type: string
                    example: 2531329f-fb09-4ef7-887e-84e648214436
      callbacks:
        # the name `onData` is a convenience locator
        onData:
          # when data is sent, it will be sent to the `callbackUrl` provided
          # when making the subscription PLUS the suffix `/data`
          '{$request.query.callbackUrl}/data':
            post:
              requestBody:
                description: subscription payload
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                        userData:
                          type: string
              responses:
                '202':
                  description: |
                    Your server implementation should return this HTTP status code
                    if the data was received successfully
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          202-onData-message:
                            type: string
                    application/xml:
                      schema:
                        type: object
                        properties:
                          202-onData-message-xml:
                            type: string
                '204':
                  description: |
                    Your server should return this HTTP status code if no longer interested
                    in further updates
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          204-onData-message:
                            type: string
        onNotification:
          '{$request.query.callbackUrl}/notification':
            get:
              requestBody:
                description: notification payload
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        message:
                          type: string
              responses:
                '202':
                  description: |
                    Your server implementation should return this HTTP status code
                    if the data was received successfully
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          202-onNotification-message:
                            type: string
                '404':
                  description: |
                    Your server should return this HTTP status code if no longer interested
                    in further updates
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          404-onNotification-message:
                            type: string
        onError:
          '{$request.query.callbackUrl}/error':
            delete:
              requestBody:
                description: error payload
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        message:
                          type: string
              responses:
                '401':
                  description: |
                    Your server implementation should return this HTTP status code
                    if the data was received successfully
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          401-onError-message:
                            type: string
  /process-order:
    post:
      summary: Submit an order for processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                callbackUrl:
                  type: string
                  format: uri
      responses:
        "202":
          description: Order accepted for processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  estimatedCompletionTime:
                    type: string
                    format: date-time
      callbacks:
        orderProcessed:
          "{$request.body#/callbackUrl}":
            post:
              requestBody:
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        orderId:
                          type: string
                        status:
                          type: string
                        completionTime:
                          type: string
                          format: date-time
              responses:
                "200":
                  description: Your server returns this code if it accepts the callback
