<template>
  <div
    v-if="showTryIt"
    class="tryit-wrapper"
    :data-testid="`tryit-wrapper-${data.id}`"
  >
    <div
      class="tryit-header"
      :class="{ 'no-body': sectionBodyEmpty }"
    >
      <div class="method-path">
        <MethodBadge
          :method="data.method"
          size="small"
        />
        <span class="path">{{ data.path }}</span>
      </div>

      <TryItDropdown
        v-if="data.path"
        class="tryit-button-dropdown"
        :data="data"
        :is-loading="apiCallLoading"
        @tryit-api-call="doApiCall"
      />
    </div>

    <div
      v-if="!sectionBodyEmpty"
      class="tryit-body"
      :data-testid="`tryit-body-${data.id}`"
    >
      <TryItAuth
        ref="auth2ComponentTemplate"
        :data="data"
        @security-scheme-changed="securitySchemeChanged"
      />

      <TryItParams
        :data="data"
        param-type="path"
        @request-path-changed="requestPathChanged"
      />

      <TryItParams
        :data="data"
        param-type="query"
        @request-query-changed="requestQueryChanged"
      />

      <TryItParams
        :data="data"
        :exclude-header-list="authHeaderNameList"
        param-type="headers"
        @request-headers-changed="requestHeadersChanged"
      />

      <TryItParams
        v-model="excludeNotRequired"
        :content-type="contentType"
        :data="data"
        param-type="body"
        :request-body="currentRequestBody"
        @request-body-changed="requestBodyChanged"
      />

      <TryItResponse
        v-if="response || responseError"
        :data-id="data.id"
        :mask-rules="maskRules"
        :response="response"
        :response-error="responseError"
        :response-schemas="data.responses ?? []"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { inject, computed, ref, watch, useTemplateRef } from 'vue'
import type { PropType, Ref } from 'vue'
import TryItDropdown from './TryItDropdown.vue'
import { getRequestHeaders, getSampleHeaders, getFormattedBody, getSamplePath, getSampleQuery, flattenMultipartFields } from '@/utils'
import type { IHttpOperation } from '@stoplight/types'
import type { SecuritySchemeMaskRule } from '@/types'
import MethodBadge from '@/components/common/MethodBadge.vue'
import TryItAuth from './TryItAuth.vue'
import TryItParams from './TryItParams.vue'
import TryItResponse from './TryItResponse.vue'
import type { RequestBody } from '@/types'

const props = defineProps({
  data: {
    type: Object as PropType<IHttpOperation>,
    required: true,
  },
  serverUrl: {
    type: String,
    required: true,
  },
  requestBody: {
    type: Object as PropType<RequestBody>,
    default: () => ({ text: '' }),
  },
  /* headers generated by auth token changes in TryItAuth */
  authHeaders: {
    type: Array as PropType<Array<Record<string, string>>>,
    default: () => [],
  },
  /* query portion generated by auth token changes in TryItAuth */
  authQuery: {
    type: String,
    default: '',
  },
  /* mask rules derived from the operation's security schemes */
  maskRules: {
    type: Array as PropType<SecuritySchemeMaskRule[]>,
    default: () => [],
  },
  contentType: {
    type: String,
    default: '',
  },
})

const authComponentRef = useTemplateRef('auth2ComponentTemplate')

const excludeNotRequired = defineModel({
  type: Boolean,
  default: true,
})

const emit = defineEmits<{
  (e: 'request-path-changed', newPath: string): void
  (e: 'request-query-changed', newPath: string): void
  (e: 'request-headers-changed', newHeaders: Array<Record<string, string>>): void
  (e: 'request-body-changed', newBody: RequestBody): void
  (e: 'security-scheme-changed', newScheme: string): void
}>()




const securitySchemeChanged = (newSecurityScheme: string) => {
  emit('security-scheme-changed', newSecurityScheme)
}

const authHeaderNameList = computed<string[]>(() => props.authHeaders.map(({ name }) => name).filter((name): name is string => !!name) ?? [])

const response = ref<Response | undefined>()
const responseError = ref<Error>()

const currentServerUrl = ref<string>(props.serverUrl)

const currentRequestPath = ref<string>('')

const currentRequestQuery = ref<string>('')

const currentRequestHeaders = ref<Array<Record<string, string>>>([])

const currentRequestBody = ref<RequestBody>({ isBinary: false, content: '' })

const apiCallLoading = ref(false)

// hide body section if none of the params are present
const sectionBodyEmpty = computed((): boolean =>
  (!props.data.servers || !props.data.servers.some(s => s.variables)) &&
  (!props.data.request?.query || !props.data.request?.query.length) &&
  (!props.data.request?.path || !props.data.request?.path.length) &&
  (!props.data.request?.headers || !props.data.request?.headers.length) &&
  (!props.data.security?.length) &&
  (!currentRequestBody.value?.content?.length && !currentRequestBody.value?.isBinary) &&
  !response.value &&
  !responseError.value,
)

const requestPathChanged = (newPath: string) => {
  currentRequestPath.value = newPath
  emit('request-path-changed', newPath)
}

const requestQueryChanged = (newQuery: string) => {
  currentRequestQuery.value = newQuery
  emit('request-query-changed', newQuery)
}

const requestHeadersChanged = (newHeaderList: Array<Record<string, string>>) => {
  currentRequestHeaders.value = newHeaderList
  emit('request-headers-changed', newHeaderList)
}

const requestBodyChanged = (newBody: RequestBody) => {
  currentRequestBody.value = newBody
  emit('request-body-changed', newBody)
}

// this is tryout state requested by property passed
const hideTryIt = inject<Ref<boolean>>('hide-tryit', ref(false))
const hideInsomniaTryIt = inject<Ref<boolean>>('hide-insomnia-tryit', ref(false))

/**
 * read file into binary buffer
 * @param file
 */
const readFileAsArrayBuffer = (file: File) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()

    reader.onload = (event) => {
      resolve(event.target?.result) // The ArrayBuffer is in event.target.result
    }

    reader.onerror = (error) => {
      reject(error) // Handle potential errors during reading
    }

    reader.readAsArrayBuffer(file) // Start reading the file
  })
}

/**
 * Perform actual fetch to the api and prepare results/errors for displaying
 * @param callAsIs when true, we do not do any modifications of the headers for GET requests, otherwise we attempt to convert get to simple request by removing 'content-type' header
 */
const doApiCall = async (callAsIs = false) => {

  const isGet = props.data.method.toUpperCase() === 'GET'

  // now we need to call uth2ClientCredentialsAuth is present, it will set headerMaps in useAuth composable, so we do not need to do anything other than call it and wait for it to finish
  if (authComponentRef.value && authComponentRef.value.auth2ClientCredentialsAuth) {
    try {
      const tokenResp = await authComponentRef.value.auth2ClientCredentialsAuth()
      if (tokenResp && !tokenResp.ok) {
        response.value = tokenResp
        throw new Error(`Error: ${tokenResp.status} ${tokenResp.statusText}`)
      }
    } catch (error: any) {
      responseError.value = error
      apiCallLoading.value = false
      return
    }
  }

  try {
    apiCallLoading.value = true
    const url = new URL(`${currentServerUrl.value}${currentRequestPath.value}`.replaceAll('{', '').replaceAll('}', ''))
    let queryStr = currentRequestQuery.value
    url.search = queryStr

    const headers = [
      ...getRequestHeaders(props.data),
      ...currentRequestHeaders.value,
      ...(props.authHeaders || []),
    ].reduce((acc, current) => {
      if (current.name && current.value !== undefined) {
        acc[callAsIs === false && isGet ? current.name.toLowerCase() : current.name] = current.value
      }
      return acc
    }, {})

    let { body: textBody } = getFormattedBody(headers, currentRequestBody.value)
    let binaryBody = null
    try {
      if (currentRequestBody.value.isBinary && currentRequestBody.value.content && currentRequestBody.value.content?.length > 0) {
        const file = (currentRequestBody.value.content[0] as File)
        binaryBody = new Uint8Array(await readFileAsArrayBuffer(file) as Buffer)
      }
    } catch (error: any) {
      responseError.value = error
      apiCallLoading.value = false
      return
    }

    let formDataBody: FormData | null = null
    if (currentRequestBody.value.isMultipart) {
      formDataBody = new FormData()
      flattenMultipartFields(currentRequestBody.value.formFields).forEach(part => {
        if (part.kind === 'file' && part.file) {
          formDataBody!.append(part.name, part.file)
        } else if (part.kind === 'json') {
          formDataBody!.append(part.name, new Blob([part.value ?? ''], { type: part.contentType ?? 'application/json' }))
        } else if (part.value !== undefined) {
          formDataBody!.append(part.name, part.value)
        }
      })

      // the browser must set Content-Type itself (with the multipart boundary) - any explicit
      // value here (from getRequestHeaders' default, or a user-added header) breaks the request
      const contentTypeKey = Object.keys(headers).find(key => key.toLowerCase() === 'content-type')
      if (contentTypeKey) {
        delete headers[contentTypeKey]
      }
    }

    // first time we call GET - we will try to convert to simple request
    if (callAsIs === false && isGet) {
      if (headers['content-type']) {
        delete headers['content-type']
      }
    }
    if (props.authQuery) {
      queryStr += (currentRequestQuery.value ? '&' : '?') + props.authQuery
    }

    const getBody = textBody || binaryBody || formDataBody

    const myResponse = await fetch(url.href, {
      method: String(props.data.method).toUpperCase(),
      cache: 'no-cache',
      headers,
      ...(getBody ? { body: getBody } : null),
    })
    response.value = myResponse

  } catch (error: any) {
    // get request converted to simple request fails, let's try non-modified request and see
    if (!callAsIs && isGet) {
      doApiCall(true)
      return
    }

    responseError.value = error
  } finally {
    apiCallLoading.value = false
  }
}

/**
 * Hide try-it section if:
 * - `hideTryIt` and `hideInsomniaTryIt` props are explicitly true
 * - or `data.servers` is empty, which means that the spec does not have any servers defined
 * - or `serverUrl` prop is not provided, so try-it snippet can't be generated
 */
const showTryIt = computed((): boolean => {
  const specHasServers = Array.isArray(props.data.servers) && props.data.servers.length > 0
  return (!hideTryIt.value || !hideInsomniaTryIt.value) && (!!props.serverUrl || specHasServers)
})

watch(() => props.serverUrl, () => {
  currentServerUrl.value = props.serverUrl
})

watch(() => props.requestBody, (body) => {
  currentRequestBody.value = body
}, { immediate: true })

watch(() => (props.data.id), () => {
  currentRequestPath.value = getSamplePath(props.data)
  currentRequestQuery.value = getSampleQuery(props.data)
  currentRequestHeaders.value = getSampleHeaders({ data: props.data, excludeHeaderList: authHeaderNameList.value })
  response.value = undefined
  responseError.value = undefined
}, { immediate: true })

</script>

<style lang="scss" scoped>
.tryit-wrapper {
  .tryit-header {
    background-color: var(--kui-color-background, $kui-color-background);
    border: var(--kui-border-width-10, $kui-border-width-10) solid var(--kui-color-border, $kui-color-border);
    border-top-left-radius: var(--kui-border-radius-30, $kui-border-radius-30);
    border-top-right-radius: var(--kui-border-radius-30, $kui-border-radius-30);
    display: flex;
    flex-direction: column;
    gap: var(--kui-space-30, $kui-space-30);
    padding: var(--kui-space-50, $kui-space-50);

    .method-path {
      align-items: center;
      display: flex;
      gap: var(--kui-space-30, $kui-space-30);
    }

    .path {
      font-family: var(--kui-font-family-code, $kui-font-family-code);
      font-size: var(--kui-font-size-30, $kui-font-size-30);
      font-weight: var(--kui-font-weight-semibold, $kui-font-weight-semibold);
      line-height: var(--kui-line-height-30, $kui-line-height-30);
      overflow-wrap: anywhere;
    }

    @media (min-width: $kui-breakpoint-mobile) {
      align-items: center;
      flex-direction: row;

      .tryit-button-dropdown {
        margin-left: var(--kui-space-auto, $kui-space-auto);
      }
    }

    &.no-body {
      border-bottom-left-radius: var(--kui-border-radius-30, $kui-border-radius-30);
      border-bottom-right-radius: var(--kui-border-radius-30, $kui-border-radius-30);
    }
  }

  .tryit-body {
    background-color: var(--kui-color-background-neutral-weakest, $kui-color-background-neutral-weakest);
    border: var(--kui-border-width-10, $kui-border-width-10) solid var(--kui-color-border, $kui-color-border);
    border-bottom-left-radius: var(--kui-border-radius-30, $kui-border-radius-30);
    border-bottom-right-radius: var(--kui-border-radius-30, $kui-border-radius-30);
    border-top: 0px;
    padding: var(--kui-space-40, $kui-space-40);
  }
}
</style>
