name: Cleanup PR preview packages
on:
  workflow_dispatch:

  schedule:
    - cron: '0 2/6 * * 6,0'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  npmjs:
    uses: ./.github/workflows/npmjs.yaml
    with:
      action: cleanup-previews
    secrets: inherit

