name: Cleanup PR preview packages
on:
  workflow_dispatch:

  schedule:
    - cron: '0 2/6 * * 6,0'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  npmjs:
    uses: ./.github/workflows/npmjs.yaml
    with:
      action: cleanup-previews
      github_token: ${{ secrets.SPEC_RENDERER_BOT_PAT }}
