name: PR Audit
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-audit:
    name: Audit
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/

      - name: PR Audit
        uses: Kong/public-shared-actions/pr-previews/audit@ec4458822419049fade832603fef9a9874af877a
        if: github.actor != 'renovate[bot]'
        with:
          renovate-pr-author: renovate[bot]
