name: Publish

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Tests
    uses: ./.github/workflows/test.yaml

  publish:
      name: Build and Publish
      needs: [run-tests]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            token: ${{ secrets.KONGPONENTS_BOT_PAT }}

        - name: Setup git
          run: |
            git config --global user.email "konnectx-engineers+kongponents-bot@konghq.com"
            git config --global user.name 'kongponents-bot'

        - name: Create .npmrc
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN_PRIVATE_PUBLISH }}
          # Reference the env variable NPM_TOKEN here, not the secret
          run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

        - name: Setup PNPM with Dependencies
          uses: ./.github/actions/setup-pnpm-with-dependencies/

        - name: Download Build Artifacts
          uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
          with:
            name: spec-renderer-build-output-artifact
            path: ./dist

        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@c4a2fa890676fc2db25ad0aacd8ab4a0f1f4c024 # v4.2.1
          env:
            # Since branch protections are on (pushing commits) you need to use a bot PAT
            GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN_PRIVATE_PUBLISH }}
